#!/bin/bash
set -e

echo "============================================"
echo "wp-hugo-static Setup Script"
echo "============================================"
echo ""

if [ -f .env ]; then
    echo "Warning: .env file already exists."
    read -p "Overwrite? (y/N): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "Domain Configuration"
echo "--------------------"
echo ""
echo "NOTE: You need to configure TWO separate domains:"
echo ""
echo "1. PUBLIC DOMAIN - Where your static Hugo site will be deployed"
echo "   (e.g., blog.yourdomain.com or yoursite.pages.dev)"
echo "   This is what visitors will see."
echo ""
echo "2. PRIVATE DOMAIN - For accessing WordPress admin via Tailscale"
echo "   (e.g., wordpress.your-tailnet.ts.net)"
echo "   This is ONLY for you to write/manage content."
echo "   WordPress is NOT publicly accessible - only via your Tailscale network."
echo ""
read -p "Public Hugo site domain (e.g., blog.yourdomain.com): " PUBLIC_DOMAIN
read -p "Private WordPress domain for Tailscale (e.g., wordpress.your-tailnet.ts.net): " PRIVATE_DOMAIN

echo ""
echo "Cloudflare Configuration"
echo "-----------------------"
read -p "Cloudflare API Token (for Cloudflare Pages deployment): " CF_API_TOKEN
read -p "Cloudflare Account ID: " CF_ACCOUNT_ID
read -p "Cloudflare Pages Project Name: " CF_PROJECT

echo ""
echo "Database Configuration"
echo "----------------------"
DB_PASSWORD=$(openssl rand -hex 32)
DB_ROOT_PASSWORD=$(openssl rand -hex 32)
echo "Generated secure database passwords."

echo ""
echo "GitHub Configuration"
echo "--------------------"
read -p "GitHub repository (owner/repo): " GITHUB_REPO
read -p "GitHub Personal Access Token (for webhook): " GITHUB_TOKEN

echo ""
echo "Hugo Site Configuration"
echo "-----------------------"
read -p "Site Title: " SITE_TITLE
read -p "Author Name: " AUTHOR_NAME
read -p "Author Email: " AUTHOR_EMAIL

echo ""
echo "Giscus Comments Configuration"
echo "-----------------------------"
read -p "Giscus Repo (owner/repo): " GISCUS_REPO
read -p "Giscus Repo ID: " GISCUS_REPO_ID
read -p "Giscus Category: " GISCUS_CATEGORY
read -p "Giscus Category ID: " GISCUS_CATEGORY_ID

echo ""
echo "Backup Configuration"
echo "---------------------"
read -p "Backup directory path: " BACKUP_DIR

echo ""
echo "============================================"
echo "Generating .env file..."
echo "============================================"

cat > .env << EOF
# Generated by setup.sh on $(date -Iseconds)

# Domain Configuration
# PUBLIC_DOMAIN: Where your static Hugo site is deployed (Cloudflare Pages)
PUBLIC_DOMAIN=${PUBLIC_DOMAIN}

# PRIVATE_DOMAIN: Tailscale domain for WordPress admin access (not publicly accessible)
# This is used for WordPress WP_HOME/WP_SITEURL configuration
WP_HOST=${PRIVATE_DOMAIN}

# Cloudflare API Token (for Cloudflare Pages deployment)
CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}

# Database Configuration
DB_PASSWORD=${DB_PASSWORD}
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

# Backup Configuration
BACKUP_DIR=${BACKUP_DIR}

# GitHub Actions / Webhook
GITHUB_TOKEN=${GITHUB_TOKEN}
GITHUB_REPO=${GITHUB_REPO}

# Cloudflare Pages Deployment
CLOUDFLARE_PAGES_API_TOKEN=${CF_API_TOKEN}
CLOUDFLARE_ACCOUNT_ID=${CF_ACCOUNT_ID}
CLOUDFLARE_PAGES_PROJECT=${CF_PROJECT}

# Hugo Configuration
SITE_TITLE="${SITE_TITLE}"
AUTHOR_NAME="${AUTHOR_NAME}"
AUTHOR_EMAIL="${AUTHOR_EMAIL}"

# Giscus Comments
GISCUS_REPO=${GISCUS_REPO}
GISCUS_REPO_ID=${GISCUS_REPO_ID}
GISCUS_CATEGORY=${GISCUS_CATEGORY}
GISCUS_CATEGORY_ID=${GISCUS_CATEGORY_ID}
EOF

echo "Created .env file."

echo ""
echo "============================================"
echo "Updating hugo.toml..."
echo "============================================"

sed -i "s|baseURL = 'https://example.com'|baseURL = 'https://${PUBLIC_DOMAIN}'|g" hugo-site/hugo.toml
sed -i "s|title = 'My Site'|title = '${SITE_TITLE}'|g" hugo-site/hugo.toml
sed -i "s|AUTHOR_NAME|${AUTHOR_NAME}|g" hugo-site/hugo.toml
sed -i "s|GISCUS_REPO|${GISCUS_REPO}|g" hugo-site/hugo.toml
sed -i "s|GISCUS_REPO_ID|${GISCUS_REPO_ID}|g" hugo-site/hugo.toml
sed -i "s|GISCUS_CATEGORY|${GISCUS_CATEGORY}|g" hugo-site/hugo.toml
sed -i "s|GISCUS_CATEGORY_ID|${GISCUS_CATEGORY_ID}|g" hugo-site/hugo.toml

echo "Updated hugo.toml with your configuration."

echo ""
echo "============================================"
echo "Setup Complete!"
echo "============================================"
echo ""
echo "Next steps:"
echo "1. Review .env file: cat .env"
echo "2. Start WordPress: docker compose up -d --build"
echo "3. Complete WordPress installation in browser"
echo "4. Configure GitHub secrets (see README)"
echo "5. Set up Tailscale on your VM"
echo ""
echo "For full instructions, see README.md"